
package com.ird.portal.fds.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2021-03-16T17:10:52.433+08:00
 * Generated source version: 3.0.16
 * 
 */
public final class FDSService_Port1_Client {

    private static final QName SERVICE_NAME = new QName("urn:dsat.gov.mo:fds/ws", "FDSService");

    private static final Logger logger = LoggerFactory.getLogger(FDSService_Port1_Client.class);

    private FDSService_Port1_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = FDSService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                logger.error("wsdlFile >>>>>>>>>",e);
            }
        }
      
        FDSService_Service ss = new FDSService_Service(wsdlURL, SERVICE_NAME);
        FDSService port = ss.getPort1();  
        
        {
        System.out.println("Invoking resetFileBatch...");
        String _resetFileBatch_txnNo = "";
        try {
            port.resetFileBatch(_resetFileBatch_txnNo);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadPhotoData...");
        Photo _uploadPhotoData_photo = null;
        try {
            PhotoResult _uploadPhotoData__return = port.uploadPhotoData(_uploadPhotoData_photo);
            System.out.println("uploadPhotoData.result=" + _uploadPhotoData__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getOperationDocsAndFeesOL...");
        OperationDocsAndFeesOLReq _getOperationDocsAndFeesOL_operationDocsAndFeesOLReq = null;
        try {
            OperationDocsAndFeesOLRsp _getOperationDocsAndFeesOL__return = port.getOperationDocsAndFeesOL(_getOperationDocsAndFeesOL_operationDocsAndFeesOLReq);
            System.out.println("getOperationDocsAndFeesOL.result=" + _getOperationDocsAndFeesOL__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking freeDayEnd...");
        String _freeDayEnd_zoneCode = "";
        javax.xml.datatype.XMLGregorianCalendar _freeDayEnd_paymentDate = null;
        try {
            port.freeDayEnd(_freeDayEnd_zoneCode, _freeDayEnd_paymentDate);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTransactions...");
        java.util.List<String> _getTransactions_txnNos = null;
        java.util.List<Transaction> _getTransactions__return = port.getTransactions(_getTransactions_txnNos);
        System.out.println("getTransactions.result=" + _getTransactions__return);


        }
        {
        System.out.println("Invoking checkUpdateTransactionAction...");
        java.util.List<String> _checkUpdateTransactionAction_txnNoList = null;
        String _checkUpdateTransactionAction_selectUid = "";
        port.checkUpdateTransactionAction(_checkUpdateTransactionAction_txnNoList, _checkUpdateTransactionAction_selectUid);


        }
        {
        System.out.println("Invoking getRelateTransactions...");
        String _getRelateTransactions_txnNo = "";
        java.util.List<Transaction> _getRelateTransactions__return = port.getRelateTransactions(_getRelateTransactions_txnNo);
        System.out.println("getRelateTransactions.result=" + _getRelateTransactions__return);


        }
        {
        System.out.println("Invoking completeTransaction...");
        String _completeTransaction_txnNo = "";
        try {
            port.completeTransaction(_completeTransaction_txnNo);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getIssueOrgs...");
        java.util.List<IssueOrg> _getIssueOrgs__return = port.getIssueOrgs();
        System.out.println("getIssueOrgs.result=" + _getIssueOrgs__return);


        }
        {
        System.out.println("Invoking deselectTransactionActionGroupEx...");
        TransActionGroupReq _deselectTransactionActionGroupEx_transActionGroupReq = null;
        ReturnObject _deselectTransactionActionGroupEx__return = port.deselectTransactionActionGroupEx(_deselectTransactionActionGroupEx_transActionGroupReq);
        System.out.println("deselectTransactionActionGroupEx.result=" + _deselectTransactionActionGroupEx__return);


        }
        {
        System.out.println("Invoking getStreets...");
        java.util.List<Street> _getStreets__return = port.getStreets();
        System.out.println("getStreets.result=" + _getStreets__return);


        }
        {
        System.out.println("Invoking getDepartments...");
        java.util.List<Department> _getDepartments__return = port.getDepartments();
        System.out.println("getDepartments.result=" + _getDepartments__return);


        }
        {
        System.out.println("Invoking getTransactionForIssues...");
        java.util.List<String> _getTransactionForIssues_txnNos = null;
        String _getTransactionForIssues_zoneCode = "";
        String _getTransactionForIssues_serviceZoneCode = "";
        java.util.List<TransactionForIssue> _getTransactionForIssues__return = port.getTransactionForIssues(_getTransactionForIssues_txnNos, _getTransactionForIssues_zoneCode, _getTransactionForIssues_serviceZoneCode);
        System.out.println("getTransactionForIssues.result=" + _getTransactionForIssues__return);


        }
        {
        System.out.println("Invoking getNextDateProfile...");
        GetNextDateProfileRequest _getNextDateProfile_parameters = null;
        DateProfile _getNextDateProfile__return = port.getNextDateProfile(_getNextDateProfile_parameters);
        System.out.println("getNextDateProfile.result=" + _getNextDateProfile__return);


        }
        {
        System.out.println("Invoking submitTransactionDetails...");
        TransactionDetails _submitTransactionDetails_transactionDetails = null;
        try {
            port.submitTransactionDetails(_submitTransactionDetails_transactionDetails);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRequiringDocsCount...");
        long _getRequiringDocsCount_docId = 0;
        int _getRequiringDocsCount__return = port.getRequiringDocsCount(_getRequiringDocsCount_docId);
        System.out.println("getRequiringDocsCount.result=" + _getRequiringDocsCount__return);


        }
        {
        System.out.println("Invoking createTransactionDto...");
        CreateTransDto _createTransactionDto_createTransDto = null;
        try {
            Transaction _createTransactionDto__return = port.createTransactionDto(_createTransactionDto_createTransDto);
            System.out.println("createTransactionDto.result=" + _createTransactionDto__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCaseIDs...");
        int _getCaseIDs_count = 0;
        try {
            java.util.List<String> _getCaseIDs__return = port.getCaseIDs(_getCaseIDs_count);
            System.out.println("getCaseIDs.result=" + _getCaseIDs__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getExemptPaymentStatus...");
        String _getExemptPaymentStatus_txnNo = "";
        try {
            String _getExemptPaymentStatus__return = port.getExemptPaymentStatus(_getExemptPaymentStatus_txnNo);
            System.out.println("getExemptPaymentStatus.result=" + _getExemptPaymentStatus__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking submitPayment...");
        Transaction _submitPayment_transaction = null;
        CallSubmitPaymentAdditional _submitPayment_callSubmitPaymentAdditional = null;
        try {
            port.submitPayment(_submitPayment_transaction, _submitPayment_callSubmitPaymentAdditional);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking approveSPProecss...");
        ApproveReq _approveSPProecss_approveReq = null;
        try {
            ReturnObject _approveSPProecss__return = port.approveSPProecss(_approveSPProecss_approveReq);
            System.out.println("approveSPProecss.result=" + _approveSPProecss__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking completeDayEnd...");
        String _completeDayEnd_zoneCode = "";
        javax.xml.datatype.XMLGregorianCalendar _completeDayEnd_paymentDate = null;
        try {
            port.completeDayEnd(_completeDayEnd_zoneCode, _completeDayEnd_paymentDate);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking execProcedure...");
        ProceInput _execProcedure_proceInput = null;
        try {
            ProceOutput _execProcedure__return = port.execProcedure(_execProcedure_proceInput);
            System.out.println("execProcedure.result=" + _execProcedure__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRubricas...");
        String _getRubricas_receiptaCode = "";
        String _getRubricas_rubricaCode = "";
        java.util.List<Rubrica> _getRubricas__return = port.getRubricas(_getRubricas_receiptaCode, _getRubricas_rubricaCode);
        System.out.println("getRubricas.result=" + _getRubricas__return);


        }
        {
        System.out.println("Invoking getIssueZone...");
        try {
            java.util.List<Zone> _getIssueZone__return = port.getIssueZone();
            System.out.println("getIssueZone.result=" + _getIssueZone__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking appendTransactionDocs...");
        TransDocsReq _appendTransactionDocs_transDocsReq = null;
        try {
            TransDocsRsp _appendTransactionDocs__return = port.appendTransactionDocs(_appendTransactionDocs_transDocsReq);
            System.out.println("appendTransactionDocs.result=" + _appendTransactionDocs__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getZones...");
        java.util.List<Zone> _getZones__return = port.getZones();
        System.out.println("getZones.result=" + _getZones__return);


        }
        {
        System.out.println("Invoking findServiceOperations...");
        long _findServiceOperations_receiptaId = 0;
        try {
            java.util.List<ViewServiceOperation> _findServiceOperations__return = port.findServiceOperations(_findServiceOperations_receiptaId);
            System.out.println("findServiceOperations.result=" + _findServiceOperations__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateSPStatusForBatch...");
        java.util.List<String> _updateSPStatusForBatch_txnNos = null;
        java.util.List<String> _updateSPStatusForBatch_serviceActionTypes = null;
        String _updateSPStatusForBatch_uid = "";
        port.updateSPStatusForBatch(_updateSPStatusForBatch_txnNos, _updateSPStatusForBatch_serviceActionTypes, _updateSPStatusForBatch_uid);


        }
        {
        System.out.println("Invoking loadBusiFileData...");
        BusiFileDataParam _loadBusiFileData_busiFileDataParam = null;
        try {
            BusiFileDataInfo _loadBusiFileData__return = port.loadBusiFileData(_loadBusiFileData_busiFileDataParam);
            System.out.println("loadBusiFileData.result=" + _loadBusiFileData__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getIDTypes...");
        java.util.List<IDType> _getIDTypes__return = port.getIDTypes();
        System.out.println("getIDTypes.result=" + _getIDTypes__return);


        }
        {
        System.out.println("Invoking getServiceFees...");
        String _getServiceFees_incomeReceiptaCode = "";
        String _getServiceFees_incomeRubricaCode = "";
        String _getServiceFees_groupCode = "";
        String _getServiceFees_code = "";
        java.util.List<ServiceFee> _getServiceFees__return = port.getServiceFees(_getServiceFees_incomeReceiptaCode, _getServiceFees_incomeRubricaCode, _getServiceFees_groupCode, _getServiceFees_code);
        System.out.println("getServiceFees.result=" + _getServiceFees__return);


        }
        {
        System.out.println("Invoking searchDepartment...");
        String _searchDepartment_loginId = "";
        Department _searchDepartment__return = port.searchDepartment(_searchDepartment_loginId);
        System.out.println("searchDepartment.result=" + _searchDepartment__return);


        }
        {
        System.out.println("Invoking checkDayEndPrecondition...");
        javax.xml.datatype.XMLGregorianCalendar _checkDayEndPrecondition_dayEndDate = null;
        String _checkDayEndPrecondition_zoneCode = "";
        try {
            java.util.List<UserProfile> _checkDayEndPrecondition__return = port.checkDayEndPrecondition(_checkDayEndPrecondition_dayEndDate, _checkDayEndPrecondition_zoneCode);
            System.out.println("checkDayEndPrecondition.result=" + _checkDayEndPrecondition__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDayEndOrBalanceCount...");
        String _getDayEndOrBalanceCount_loginId = "";
        String _getDayEndOrBalanceCount_zoneCode = "";
        int _getDayEndOrBalanceCount__return = port.getDayEndOrBalanceCount(_getDayEndOrBalanceCount_loginId, _getDayEndOrBalanceCount_zoneCode);
        System.out.println("getDayEndOrBalanceCount.result=" + _getDayEndOrBalanceCount__return);


        }
        {
        System.out.println("Invoking isNeedToSendSMS...");
        String _isNeedToSendSMS_idTypeCode = "";
        String _isNeedToSendSMS_idNo = "";
        long _isNeedToSendSMS_docId = 0;
        long _isNeedToSendSMS_vId = 0;
        String _isNeedToSendSMS_driverLicType = "";
        String _isNeedToSendSMS_driverLicNo = "";
        String _isNeedToSendSMS_categoryTypeCode = "";
        String _isNeedToSendSMS_categoryNo = "";
        String _isNeedToSendSMS_uid = "";
        try {
            boolean _isNeedToSendSMS__return = port.isNeedToSendSMS(_isNeedToSendSMS_idTypeCode, _isNeedToSendSMS_idNo, _isNeedToSendSMS_docId, _isNeedToSendSMS_vId, _isNeedToSendSMS_driverLicType, _isNeedToSendSMS_driverLicNo, _isNeedToSendSMS_categoryTypeCode, _isNeedToSendSMS_categoryNo, _isNeedToSendSMS_uid);
            System.out.println("isNeedToSendSMS.result=" + _isNeedToSendSMS__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateTransaction...");
        Transaction _updateTransaction_transaction = null;
        port.updateTransaction(_updateTransaction_transaction);


        }
        {
        System.out.println("Invoking createSlaveTransaction...");
        String _createSlaveTransaction_serviceOperationCode = "";
        String _createSlaveTransaction_txnNo = "";
        String _createSlaveTransaction_loginId = "";
        String _createSlaveTransaction_incomeIP = "";
        boolean _createSlaveTransaction_completeOnCreation = false;
        try {
            Transaction _createSlaveTransaction__return = port.createSlaveTransaction(_createSlaveTransaction_serviceOperationCode, _createSlaveTransaction_txnNo, _createSlaveTransaction_loginId, _createSlaveTransaction_incomeIP, _createSlaveTransaction_completeOnCreation);
            System.out.println("createSlaveTransaction.result=" + _createSlaveTransaction__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getIssueLicenseTxnnos...");
        java.util.List<String> _getIssueLicenseTxnnos_txnNos = null;
        String _getIssueLicenseTxnnos_zoneCode = "";
        java.util.List<String> _getIssueLicenseTxnnos__return = port.getIssueLicenseTxnnos(_getIssueLicenseTxnnos_txnNos, _getIssueLicenseTxnnos_zoneCode);
        System.out.println("getIssueLicenseTxnnos.result=" + _getIssueLicenseTxnnos__return);


        }
        {
        System.out.println("Invoking getDayEndControlView...");
        try {
            java.util.List<DayEndControlView> _getDayEndControlView__return = port.getDayEndControlView();
            System.out.println("getDayEndControlView.result=" + _getDayEndControlView__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createTransaction...");
        String _createTransaction_serviceOperationCode = "";
        String _createTransaction_loginId = "";
        String _createTransaction_incomeIP = "";
        boolean _createTransaction_completeOnCreation = false;
        try {
            Transaction _createTransaction__return = port.createTransaction(_createTransaction_serviceOperationCode, _createTransaction_loginId, _createTransaction_incomeIP, _createTransaction_completeOnCreation);
            System.out.println("createTransaction.result=" + _createTransaction__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getVehicleTypes...");
        java.util.List<VehicleType> _getVehicleTypes__return = port.getVehicleTypes();
        System.out.println("getVehicleTypes.result=" + _getVehicleTypes__return);


        }
        {
        System.out.println("Invoking getNextWorkingDay...");
        javax.xml.datatype.XMLGregorianCalendar _getNextWorkingDay_date = null;
        javax.xml.datatype.XMLGregorianCalendar _getNextWorkingDay__return = port.getNextWorkingDay(_getNextWorkingDay_date);
        System.out.println("getNextWorkingDay.result=" + _getNextWorkingDay__return);


        }
        {
        System.out.println("Invoking getServiceOperations...");
        java.util.List<ServiceOperation> _getServiceOperations__return = port.getServiceOperations();
        System.out.println("getServiceOperations.result=" + _getServiceOperations__return);


        }
        {
        System.out.println("Invoking getRequiringDocsCountByTxnNo...");
        java.util.List<String> _getRequiringDocsCountByTxnNo_txnNos = null;
        java.util.List<RequiringDocsInfo> _getRequiringDocsCountByTxnNo__return = port.getRequiringDocsCountByTxnNo(_getRequiringDocsCountByTxnNo_txnNos);
        System.out.println("getRequiringDocsCountByTxnNo.result=" + _getRequiringDocsCountByTxnNo__return);


        }
        {
        System.out.println("Invoking autoCreateAndCompleteOLTransaction...");
        CreateOnlineTransDto _autoCreateAndCompleteOLTransaction_createOnlineTransDto = null;
        try {
            CreateOnlineTransRtn _autoCreateAndCompleteOLTransaction__return = port.autoCreateAndCompleteOLTransaction(_autoCreateAndCompleteOLTransaction_createOnlineTransDto);
            System.out.println("autoCreateAndCompleteOLTransaction.result=" + _autoCreateAndCompleteOLTransaction__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking increaseTransaction...");
        String _increaseTransaction_caseId = "";
        try {
            Transaction _increaseTransaction__return = port.increaseTransaction(_increaseTransaction_caseId);
            System.out.println("increaseTransaction.result=" + _increaseTransaction__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTransactionPaymentAmount...");
        String _getTransactionPaymentAmount_txnNo = "";
        try {
            double _getTransactionPaymentAmount__return = port.getTransactionPaymentAmount(_getTransactionPaymentAmount_txnNo);
            System.out.println("getTransactionPaymentAmount.result=" + _getTransactionPaymentAmount__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDateProfiles...");
        javax.xml.datatype.XMLGregorianCalendar _getDateProfiles_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getDateProfiles_endDate = null;
        java.util.List<DateProfile> _getDateProfiles__return = port.getDateProfiles(_getDateProfiles_startDate, _getDateProfiles_endDate);
        System.out.println("getDateProfiles.result=" + _getDateProfiles__return);


        }
        {
        System.out.println("Invoking deselectTransactionActionGroup...");
        String _deselectTransactionActionGroup_txnNo = "";
        String _deselectTransactionActionGroup_serviceActionType = "";
        port.deselectTransactionActionGroup(_deselectTransactionActionGroup_txnNo, _deselectTransactionActionGroup_serviceActionType);


        }
        {
        System.out.println("Invoking getPaymentInformation...");
        String _getPaymentInformation_txnNo = "";
        try {
            PaymentInfo _getPaymentInformation__return = port.getPaymentInformation(_getPaymentInformation_txnNo);
            System.out.println("getPaymentInformation.result=" + _getPaymentInformation__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking submit...");
        Transaction _submit_transaction = null;
        try {
            port.submit(_submit_transaction);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDateProfile...");
        javax.xml.datatype.XMLGregorianCalendar _getDateProfile_date = null;
        DateProfile _getDateProfile__return = port.getDateProfile(_getDateProfile_date);
        System.out.println("getDateProfile.result=" + _getDateProfile__return);


        }
        {
        System.out.println("Invoking batchDeselectIndependentTransactionAction...");
        java.util.List<String> _batchDeselectIndependentTransactionAction_txnNos = null;
        java.util.List<String> _batchDeselectIndependentTransactionAction_serviceActionTypes = null;
        port.batchDeselectIndependentTransactionAction(_batchDeselectIndependentTransactionAction_txnNos, _batchDeselectIndependentTransactionAction_serviceActionTypes);


        }
        {
        System.out.println("Invoking getMasterTxnNos...");
        int _getMasterTxnNos_count = 0;
        try {
            java.util.List<String> _getMasterTxnNos__return = port.getMasterTxnNos(_getMasterTxnNos_count);
            System.out.println("getMasterTxnNos.result=" + _getMasterTxnNos__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking batchUpdateDTSDesc...");
        java.util.List<DTSParam> _batchUpdateDTSDesc_dtsParams = null;
        String _batchUpdateDTSDesc_loginId = "";
        port.batchUpdateDTSDesc(_batchUpdateDTSDesc_dtsParams, _batchUpdateDTSDesc_loginId);


        }
        {
        System.out.println("Invoking searchZone...");
        String _searchZone_incomeIP = "";
        Zone _searchZone__return = port.searchZone(_searchZone_incomeIP);
        System.out.println("searchZone.result=" + _searchZone__return);


        }
        {
        System.out.println("Invoking getDayEndDetails...");
        String _getDayEndDetails_zoneCode = "";
        long _getDayEndDetails_first = 0;
        long _getDayEndDetails_count = 0;
        java.util.List<DayEndDetails> _getDayEndDetails__return = port.getDayEndDetails(_getDayEndDetails_zoneCode, _getDayEndDetails_first, _getDayEndDetails_count);
        System.out.println("getDayEndDetails.result=" + _getDayEndDetails__return);


        }
        {
        System.out.println("Invoking getServices...");
        java.util.List<Service> _getServices__return = port.getServices();
        System.out.println("getServices.result=" + _getServices__return);


        }
        {
        System.out.println("Invoking updateWorkflowStatus...");
        String _updateWorkflowStatus_txnNo = "";
        String _updateWorkflowStatus_statusKey = "";
        String _updateWorkflowStatus_statusDisplayZh = "";
        String _updateWorkflowStatus_statusDisplayPt = "";
        try {
            port.updateWorkflowStatus(_updateWorkflowStatus_txnNo, _updateWorkflowStatus_statusKey, _updateWorkflowStatus_statusDisplayZh, _updateWorkflowStatus_statusDisplayPt);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking autoCreateAndCompleteTransaction...");
        java.util.List<ServiceFeeRequestVSS> _autoCreateAndCompleteTransaction_serviceFeeRequests = null;
        Payment _autoCreateAndCompleteTransaction_payment = null;
        CreateTransInfo _autoCreateAndCompleteTransaction_createTransInfo = null;
        try {
            Transaction _autoCreateAndCompleteTransaction__return = port.autoCreateAndCompleteTransaction(_autoCreateAndCompleteTransaction_serviceFeeRequests, _autoCreateAndCompleteTransaction_payment, _autoCreateAndCompleteTransaction_createTransInfo);
            System.out.println("autoCreateAndCompleteTransaction.result=" + _autoCreateAndCompleteTransaction__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking countDayEndDates...");
        String _countDayEndDates_zoneCode = "";
        long _countDayEndDates__return = port.countDayEndDates(_countDayEndDates_zoneCode);
        System.out.println("countDayEndDates.result=" + _countDayEndDates__return);


        }
        {
        System.out.println("Invoking selectTransactionActions...");
        java.util.List<TransactionActionKey> _selectTransactionActions_keys = null;
        String _selectTransactionActions_uid = "";
        port.selectTransactionActions(_selectTransactionActions_keys, _selectTransactionActions_uid);


        }
        {
        System.out.println("Invoking deselectTransactionAction...");
        String _deselectTransactionAction_txnNo = "";
        port.deselectTransactionAction(_deselectTransactionAction_txnNo);


        }
        {
        System.out.println("Invoking getOperationCodes...");
        String _getOperationCodes_loginId = "";
        java.util.List<String> _getOperationCodes__return = port.getOperationCodes(_getOperationCodes_loginId);
        System.out.println("getOperationCodes.result=" + _getOperationCodes__return);


        }
        {
        System.out.println("Invoking getTransactionInfo...");
        String _getTransactionInfo_txnNo = "";
        try {
            TransactionInfo _getTransactionInfo__return = port.getTransactionInfo(_getTransactionInfo_txnNo);
            System.out.println("getTransactionInfo.result=" + _getTransactionInfo__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateTransactionDocs...");
        TransDocsReq _updateTransactionDocs_transDocsReq = null;
        try {
            TransDocsRsp _updateTransactionDocs__return = port.updateTransactionDocs(_updateTransactionDocs_transDocsReq);
            System.out.println("updateTransactionDocs.result=" + _updateTransactionDocs__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getFeeEntryAmount...");
        String _getFeeEntryAmount_txnNo = "";
        String _getFeeEntryAmount_serviceFeeCode = "";
        try {
            double _getFeeEntryAmount__return = port.getFeeEntryAmount(_getFeeEntryAmount_txnNo, _getFeeEntryAmount_serviceFeeCode);
            System.out.println("getFeeEntryAmount.result=" + _getFeeEntryAmount__return);

        } catch (FDSException e) { 
            System.out.println("Expected exception: FDSException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
