# DSAT DEV環境
server:
  error:
    path: /error
  tomcat:
    max-http-post-size: -1
  session:
    #設置session時間為8小時
    timeout: 28800

# 網站運行模式 dev=開發,DEV=DEV環境運行,UAT=UAT環境運行,PROD=生產環境
website:
  model: dev

#jasypt加密的密匙
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7

#Spring 配置信息
spring:
  #AOP配置
  aop:
    auto: true
    proxy-target-class: true

  # jdbc 驱动配置信息
  # JDBC DataSource config
  datasource:
    #鏈接方式 JDBC,JNDI
    mode: JDBC

    #JDBC
    type: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.200.136:1433;SelectMethod=cursor;DatabaseName=IRD_WEB
    username: IRD
    password: ENC(FT0fzJBG9q0OoLEsTYH5JyTRbyx0HH3x)
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 是否一直执行。ALWAYS表示总是执行，NEVER表示不执行
    initialization-mode: ALWAYS
    # 遇到错误是否继续
    continue-on-error: true
    # SQL语句的建表语句位置
    schema:  classpath:/data/schema.sql
    # 初始化数据的文件所在位置
    data: classpath:/data/data.sql

    # Spring JNDI  datasource.jndi.name
    jndi:
      name: CLP_DEV_DS
  # JPA Configuration:
  jpa:

    # Hibernate ddl auto (create, create-drop, update, validate)
    hibernate:
      ddl-auto:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: com.ird.portal.dao.hibernate.SqlServer2012Dialect
        show_sql: false
        format_sql: false
      javax:
        persistence:
          validation:
            mode: none

  #ehcache configuration
  cache:
    ehcache:
      config: ehcache.xml

  # Use Thymeleaf 3
  thymeleaf:
    mode: HTML
    prefix: /WEB-INF/templates/
    suffix: .html
    encoding: UTF-8
    # 開發模式下 將緩存關閉
    cache: false

  # 多语言国际化
  messages:
    encoding: UTF-8

  #  jackson 配置
  jackson:
    time-zone: GMT+8
    date-format: dd/MM/yyyy

  # http 统一UTF-8，避免中文乱码
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    # http.multipart 文件上傳配置處理
    multipart:
      enabled: true
      resolveLazily: true
      max-file-size: 100MB
      max-request-size: 200MB
      file-size-threshold: 0
  #BaseServiceWS Configuration
  baseServiceWS:
    sms:
      wsdl: http://doisrvdev/sms_dev/SMSWebService.asmx?WSDL
      username: spsys_sa_dev
      #spdev123
      password: ENC(MtATBGnnUaj9IL40uynAiinMxQA0mpAN)
      domain: dsat.gov.mo

  mail:
    # 邮件服务地址
    host: smtp.qq.com
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: 2780023361@qq.com
    prot: 465
    # 授权码，就是我们刚才准备工作获取的代码
    password: iwurjibumbngddbi
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                    enable: true
                    required: true
filter:
  excludeUrls:  /login/login.html,/login/login,/triggerApi/testTriggerAPI


#CAS config
cas:
  casEnabled: false
  # 是否為Weblogic
  isWeblogic: false


#sch config
sch:
  quartzProperties:
    quartz:
      scheduler:
        instanceName: scheduler
        instanceId: AUTO
      #綫程配置
      threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 10
        threadPriority: 5

      #JobStore配置
      jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        #集群配置
        isClustered: false
        clusterCheckinInterval: 15000
        maxMisfiresToHandleAtATime: 1

        misfireThreshold: 120000
        tablePrefix: CLP_QRTZ_

        driverDelegateClass: org.quartz.impl.jdbcjobstore.MSSQLDelegate

  schedulerName: COSscheduler
  #必须的，QuartzScheduler 延时启动，应用启动完后 QuartzScheduler 再启动 兩分鈡后啓動所有scheduler
  startupDelay: 10
  applicationContextSchedulerContextKey: applicationContext
  #可选,QuartzScheduler 启动时更新己存在的Job，这样就不用每次修改targetObject后删除qrtz_job_details表对应记录了
  overwriteExistingJobs: true
  #当值为true时，自主触发运行SchedulerJob
  autoStartup: false

# 配置logback
logging:
  config: classpath:clp-logback.xml

# 報表模板基礎路徑
report:
  basepath: @web-prefix@/report
  # 報表模板路徑
  jasperreports_properties: /jasperreports_extension.properties

  templates: /template/
  isRelativePath: true


apiUrl:
  alertBlackoutAPICreateRequest: www.baidu.com
  alertBlackoutAPIUpdateRequest: www.baidu.com
  alertBlackoutAPIQueryRequest: www.baidu.com
  alertBlackoutRequestOutput: www.baidu.com
  alertBlackoutAPICancelRequest: www.baidu.com
  serviceFailureEventAPIRequest: www.baidu.com
  securityEventAPIRequest: www.baidu.com
  renewCert: www.baidu.com
  heartBeatAPIRequest: www.baidu.com


