﻿spring:
  profiles:
    active: @run.env@  #去查找appliation-dev.yml
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: WEB-INF/templates/**,WEB-INF/static/**

    # 多语言国际化
  messages:
    basename: i18n/global/messages,i18n/cbt/messages,i18n/eds/messages,i18n/rpt/messages,i18n/sch/messages,i18n/comps/messages,i18n/sys/messages,i18n/enum/messages,i18n/validation/messages,i18n/ctr/messages,i18n/inp/messages,i18n/que/messages,i18n/veh/messages,i18n/equ/messages
server:
  port: 8888
  contextPath: @web-prefix@/web

ird-web:
  version: @sysVersion@
  deployDate: @buildTime@
# vics upgrade
weblogic:
  webPrefix: @web-prefix@