
package com.ird.portal.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-30T14:27:34.769+08:00
 * Generated source version: 3.0.16
 * 
 */
public final class SMSWebServiceSoap_SMSWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://dsat/SMSwebservices/", "SMSWebService");
    private static final Logger logger = LoggerFactory.getLogger(SMSWebServiceSoap_SMSWebServiceSoap12_Client.class);

    private SMSWebServiceSoap_SMSWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SMSWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                logger.error("wsdlFile>>>>>>>>>>",e);
            }
        }

        SMSWebService ss = new SMSWebService(wsdlURL, SERVICE_NAME);
        SMSWebServiceSoap port = ss.getSMSWebServiceSoap();


        {
            System.out.println("Invoking sendSms...");
            String _sendSms_appType = "";
            String _sendSms_mobile = "666666";
            String _sendSms_content = "test";
            String _sendSms_reference = "100012";
            String _sendSms_scheduleDeliveryTime = "";
            String _sendSms__return = port.sendSms(_sendSms_appType, _sendSms_mobile, _sendSms_content, _sendSms_reference, _sendSms_scheduleDeliveryTime);
            System.out.println("sendSms.result=" + _sendSms__return);


            }
        
       /* {
        System.out.println("Invoking sendSmsByAppType...");
        java.lang.String _sendSmsByAppType_appType = "";
        java.lang.String _sendSmsByAppType_mobile = "";
        java.lang.String _sendSmsByAppType_content = "";
        java.lang.String _sendSmsByAppType_reference = "";
        java.lang.String _sendSmsByAppType_scheduleDeliveryTime = "";
        java.lang.String _sendSmsByAppType__return = port.sendSmsByAppType(_sendSmsByAppType_appType, _sendSmsByAppType_mobile, _sendSmsByAppType_content, _sendSmsByAppType_reference, _sendSmsByAppType_scheduleDeliveryTime);
        System.out.println("sendSmsByAppType.result=" + _sendSmsByAppType__return);


        }
        {
        System.out.println("Invoking echo...");
        java.lang.String _echo_echoString = "";
        java.lang.String _echo__return = port.echo(_echo_echoString);
        System.out.println("echo.result=" + _echo__return);


        }
        {
        System.out.println("Invoking queryStatus...");
        java.lang.String _queryStatus_poolIdStr = "";
        java.lang.String _queryStatus__return = port.queryStatus(_queryStatus_poolIdStr);
        System.out.println("queryStatus.result=" + _queryStatus__return);


        }
        {
        System.out.println("Invoking sendSmsBatchByAppType...");
        java.lang.String _sendSmsBatchByAppType_appType = "";
        java.lang.String _sendSmsBatchByAppType_mobile = "";
        java.lang.String _sendSmsBatchByAppType_content = "";
        java.lang.String _sendSmsBatchByAppType_reference = "";
        java.lang.String _sendSmsBatchByAppType_scheduleDeliveryTime = "";
        java.lang.String _sendSmsBatchByAppType_batchCd = "";
        java.lang.String _sendSmsBatchByAppType__return = port.sendSmsBatchByAppType(_sendSmsBatchByAppType_appType, _sendSmsBatchByAppType_mobile, _sendSmsBatchByAppType_content, _sendSmsBatchByAppType_reference, _sendSmsBatchByAppType_scheduleDeliveryTime, _sendSmsBatchByAppType_batchCd);
        System.out.println("sendSmsBatchByAppType.result=" + _sendSmsBatchByAppType__return);


        }
        {
        System.out.println("Invoking sendSms...");
        java.lang.String _sendSms_appType = "";
        java.lang.String _sendSms_mobile = "";
        java.lang.String _sendSms_content = "";
        java.lang.String _sendSms_reference = "";
        java.lang.String _sendSms_scheduleDeliveryTime = "";
        java.lang.String _sendSms__return = port.sendSms(_sendSms_appType, _sendSms_mobile, _sendSms_content, _sendSms_reference, _sendSms_scheduleDeliveryTime);
        System.out.println("sendSms.result=" + _sendSms__return);


        }
        {
        System.out.println("Invoking sendSmsBatch...");
        java.lang.String _sendSmsBatch_appType = "";
        java.lang.String _sendSmsBatch_mobile = "";
        java.lang.String _sendSmsBatch_content = "";
        java.lang.String _sendSmsBatch_reference = "";
        java.lang.String _sendSmsBatch_scheduleDeliveryTime = "";
        java.lang.String _sendSmsBatch_batchCd = "";
        java.lang.String _sendSmsBatch__return = port.sendSmsBatch(_sendSmsBatch_appType, _sendSmsBatch_mobile, _sendSmsBatch_content, _sendSmsBatch_reference, _sendSmsBatch_scheduleDeliveryTime, _sendSmsBatch_batchCd);
        System.out.println("sendSmsBatch.result=" + _sendSmsBatch__return);


        }*/

        System.exit(0);
    }

}
