package com.ird.portal.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-30T14:27:34.777+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://dsat/SMSwebservices/", name = "SMSWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SMSWebServiceSoap {

    @WebMethod(operationName = "SendSmsByAppType", action = "http://dsat/SMSwebservices/SendSmsByAppType")
    @RequestWrapper(localName = "SendSmsByAppType", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.SendSmsByAppType")
    @ResponseWrapper(localName = "SendSmsByAppTypeResponse", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.SendSmsByAppTypeResponse")
    @WebResult(name = "SendSmsByAppTypeResult", targetNamespace = "http://dsat/SMSwebservices/")
    public String sendSmsByAppType(
            @WebParam(name = "appType", targetNamespace = "http://dsat/SMSwebservices/")
                    String appType,
            @WebParam(name = "mobile", targetNamespace = "http://dsat/SMSwebservices/")
                    String mobile,
            @WebParam(name = "content", targetNamespace = "http://dsat/SMSwebservices/")
                    String content,
            @WebParam(name = "reference", targetNamespace = "http://dsat/SMSwebservices/")
                    String reference,
            @WebParam(name = "scheduleDeliveryTime", targetNamespace = "http://dsat/SMSwebservices/")
                    String scheduleDeliveryTime
    );

    @WebMethod(operationName = "Echo", action = "http://dsat/SMSwebservices/Echo")
    @RequestWrapper(localName = "Echo", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.Echo")
    @ResponseWrapper(localName = "EchoResponse", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.EchoResponse")
    @WebResult(name = "EchoResult", targetNamespace = "http://dsat/SMSwebservices/")
    public String echo(
            @WebParam(name = "echoString", targetNamespace = "http://dsat/SMSwebservices/")
                    String echoString
    );

    @WebMethod(operationName = "QueryStatus", action = "http://dsat/SMSwebservices/QueryStatus")
    @RequestWrapper(localName = "QueryStatus", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.QueryStatus")
    @ResponseWrapper(localName = "QueryStatusResponse", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.QueryStatusResponse")
    @WebResult(name = "QueryStatusResult", targetNamespace = "http://dsat/SMSwebservices/")
    public String queryStatus(
            @WebParam(name = "poolIdStr", targetNamespace = "http://dsat/SMSwebservices/")
                    String poolIdStr
    );

    @WebMethod(operationName = "SendSmsBatchByAppType", action = "http://dsat/SMSwebservices/SendSmsBatchByAppType")
    @RequestWrapper(localName = "SendSmsBatchByAppType", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.SendSmsBatchByAppType")
    @ResponseWrapper(localName = "SendSmsBatchByAppTypeResponse", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.SendSmsBatchByAppTypeResponse")
    @WebResult(name = "SendSmsBatchByAppTypeResult", targetNamespace = "http://dsat/SMSwebservices/")
    public String sendSmsBatchByAppType(
            @WebParam(name = "appType", targetNamespace = "http://dsat/SMSwebservices/")
                    String appType,
            @WebParam(name = "mobile", targetNamespace = "http://dsat/SMSwebservices/")
                    String mobile,
            @WebParam(name = "content", targetNamespace = "http://dsat/SMSwebservices/")
                    String content,
            @WebParam(name = "reference", targetNamespace = "http://dsat/SMSwebservices/")
                    String reference,
            @WebParam(name = "scheduleDeliveryTime", targetNamespace = "http://dsat/SMSwebservices/")
                    String scheduleDeliveryTime,
            @WebParam(name = "batchCd", targetNamespace = "http://dsat/SMSwebservices/")
                    String batchCd
    );

    @WebMethod(operationName = "SendSms", action = "http://dsat/SMSwebservices/SendSms")
    @RequestWrapper(localName = "SendSms", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.SendSms")
    @ResponseWrapper(localName = "SendSmsResponse", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.SendSmsResponse")
    @WebResult(name = "SendSmsResult", targetNamespace = "http://dsat/SMSwebservices/")
    public String sendSms(
            @WebParam(name = "appType", targetNamespace = "http://dsat/SMSwebservices/")
                    String appType,
            @WebParam(name = "mobile", targetNamespace = "http://dsat/SMSwebservices/")
                    String mobile,
            @WebParam(name = "content", targetNamespace = "http://dsat/SMSwebservices/")
                    String content,
            @WebParam(name = "reference", targetNamespace = "http://dsat/SMSwebservices/")
                    String reference,
            @WebParam(name = "scheduleDeliveryTime", targetNamespace = "http://dsat/SMSwebservices/")
                    String scheduleDeliveryTime
    );

    @WebMethod(operationName = "SendSmsBatch", action = "http://dsat/SMSwebservices/SendSmsBatch")
    @RequestWrapper(localName = "SendSmsBatch", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.SendSmsBatch")
    @ResponseWrapper(localName = "SendSmsBatchResponse", targetNamespace = "http://dsat/SMSwebservices/", className = "dsat.smswebservices.SendSmsBatchResponse")
    @WebResult(name = "SendSmsBatchResult", targetNamespace = "http://dsat/SMSwebservices/")
    public String sendSmsBatch(
            @WebParam(name = "appType", targetNamespace = "http://dsat/SMSwebservices/")
                    String appType,
            @WebParam(name = "mobile", targetNamespace = "http://dsat/SMSwebservices/")
                    String mobile,
            @WebParam(name = "content", targetNamespace = "http://dsat/SMSwebservices/")
                    String content,
            @WebParam(name = "reference", targetNamespace = "http://dsat/SMSwebservices/")
                    String reference,
            @WebParam(name = "scheduleDeliveryTime", targetNamespace = "http://dsat/SMSwebservices/")
                    String scheduleDeliveryTime,
            @WebParam(name = "batchCd", targetNamespace = "http://dsat/SMSwebservices/")
                    String batchCd
    );
}
