
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ird.portal.tcs.ws;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-09-14T21:43:20.140+08:00
 * Generated source version: 3.2.10
 *
 */

@javax.jws.WebService(
                      serviceName = "TCSService",
                      portName = "port1",
                      targetNamespace = "urn:dsat.gov.mo:tcs/ws",
                      wsdlLocation = "http://dsatoss/tcs/ws/TCSService?wsdl",
                      endpointInterface = "com.ird.portal.tcs.ws.TCSService")

public class Port1Impl implements TCSService {

    private static final Logger LOG = Logger.getLogger(Port1Impl.class.getName());

    /* (non-Javadoc)
     * @see TCSService#checkTaxiTrainingCourseApply(long docId, UserInfo userInfo)*
     */
    public SimpleCheckResult checkTaxiTrainingCourseApply(long docId, UserInfo userInfo) throws TCSException   {
        LOG.info("Executing operation checkTaxiTrainingCourseApply");
        System.out.println(docId);
        System.out.println(userInfo);
        try {
            SimpleCheckResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            throw new RuntimeException(ex);
        }
        //throw new TCSException("TCSException...");
    }

    /* (non-Javadoc)
     * @see TCSService#checkTrainCourseForTaxiExam(long docId, UserInfo userInfo)*
     */
    public SimpleCheckResult checkTrainCourseForTaxiExam(long docId, UserInfo userInfo) throws TCSException   {
        LOG.info("Executing operation checkTrainCourseForTaxiExam");
        System.out.println(docId);
        System.out.println(userInfo);
        try {
            SimpleCheckResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            throw new RuntimeException(ex);
        }
        //throw new TCSException("TCSException...");
    }

}
