
package com.ird.portal.tcs.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-09-14T21:43:20.126+08:00
 * Generated source version: 3.2.10
 */

@WebFault(name = "fault", targetNamespace = "urn:dsat.gov.mo:tcs/ws")
public class TCSException extends Exception {

    private Fault fault;

    public TCSException() {
        super();
    }

    public TCSException(String message) {
        super(message);
    }

    public TCSException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TCSException(String message, Fault fault) {
        super(message);
        this.fault = fault;
    }

    public TCSException(String message, Fault fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public Fault getFaultInfo() {
        return this.fault;
    }
}
