
package com.ird.portal.tcs.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-09-14T21:43:20.091+08:00
 * Generated source version: 3.2.10
 *
 */
public final class TCSService_Port1_Client {

    private static final Logger logger = LoggerFactory.getLogger(TCSService_Port1_Client.class);
    private static final QName SERVICE_NAME = new QName("urn:dsat.gov.mo:tcs/ws", "TCSService");

    private TCSService_Port1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TCSService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                logger.error("MalformedURLException:{}",e);
            }
        }

        TCSService_Service ss = new TCSService_Service(wsdlURL, SERVICE_NAME);
        TCSService port = ss.getPort1();

        {
        System.out.println("Invoking checkTaxiTrainingCourseApply...");
        long _checkTaxiTrainingCourseApply_docId = 0;
        UserInfo _checkTaxiTrainingCourseApply_userInfo = null;
        try {
            SimpleCheckResult _checkTaxiTrainingCourseApply__return = port.checkTaxiTrainingCourseApply(_checkTaxiTrainingCourseApply_docId, _checkTaxiTrainingCourseApply_userInfo);
            System.out.println("checkTaxiTrainingCourseApply.result=" + _checkTaxiTrainingCourseApply__return);

        } catch (TCSException e) {
            System.out.println("Expected exception: TCSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking checkTrainCourseForTaxiExam...");
        long _checkTrainCourseForTaxiExam_docId = 0;
        UserInfo _checkTrainCourseForTaxiExam_userInfo = null;
        try {
            SimpleCheckResult _checkTrainCourseForTaxiExam__return = port.checkTrainCourseForTaxiExam(_checkTrainCourseForTaxiExam_docId, _checkTrainCourseForTaxiExam_userInfo);
            System.out.println("checkTrainCourseForTaxiExam.result=" + _checkTrainCourseForTaxiExam__return);

        } catch (TCSException e) {
            System.out.println("Expected exception: TCSException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
