
package com.ird.portal.tcs.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-09-14T21:43:20.185+08:00
 * Generated source version: 3.2.10
 *
 */

public class TCSService_Port1_Server{

    protected TCSService_Port1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new Port1Impl();
        String address = "http://dsatwlstst:80/tcs/ws/TCSService";
        Endpoint.publish(address, implementor);
    }

}
