package com.ird.portal.tcs.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-09-14T21:43:20.169+08:00
 * Generated source version: 3.2.10
 *
 */
@WebService(targetNamespace = "urn:dsat.gov.mo:tcs/ws", name = "TCSService")
@XmlSeeAlso({ObjectFactory.class})
public interface TCSService {

    /**
     * check taxiTrainingCourse weather can apply Again
     */
    @WebMethod(action = "urn:dsat.gov.mo:tcs/ws/checkTaxiTrainingCourseApply")
    @RequestWrapper(localName = "checkTaxiTrainingCourseApply", targetNamespace = "urn:dsat.gov.mo:tcs/ws", className = "CheckTaxiTrainingCourseApply")
    @ResponseWrapper(localName = "checkTaxiTrainingCourseApplyResponse", targetNamespace = "urn:dsat.gov.mo:tcs/ws", className = "CheckTaxiTrainingCourseApplyResponse")
    @WebResult(name = "result", targetNamespace = "")
    public SimpleCheckResult checkTaxiTrainingCourseApply(
        @WebParam(name = "docId", targetNamespace = "")
        long docId,
        @WebParam(name = "userInfo", targetNamespace = "")
                UserInfo userInfo
    ) throws TCSException;

    /**
     * tpms apply should have effective
     * 				taxiTrainingCourse
     */
    @WebMethod(action = "urn:dsat.gov.mo:tcs/ws/checkTrainCourseForTaxiExam")
    @RequestWrapper(localName = "checkTrainCourseForTaxiExam", targetNamespace = "urn:dsat.gov.mo:tcs/ws", className = "CheckTrainCourseForTaxiExam")
    @ResponseWrapper(localName = "checkTrainCourseForTaxiExamResponse", targetNamespace = "urn:dsat.gov.mo:tcs/ws", className = "CheckTrainCourseForTaxiExamResponse")
    @WebResult(name = "result", targetNamespace = "")
    public SimpleCheckResult checkTrainCourseForTaxiExam(
        @WebParam(name = "docId", targetNamespace = "")
        long docId,
        @WebParam(name = "userInfo", targetNamespace = "")
                UserInfo userInfo
    ) throws TCSException;
}
