
package com.ird.portal.mega.tpms.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.16
 * 2021-02-25T09:49:25.743+08:00
 * Generated source version: 3.0.16
 */

@WebFault(name = "TPMSServiceException", targetNamespace = "http://service.tpms.dsat.mega.com/")
public class TPMSServiceException_Exception extends Exception {
    
    private TPMSServiceException tpmsServiceException;

    public TPMSServiceException_Exception() {
        super();
    }
    
    public TPMSServiceException_Exception(String message) {
        super(message);
    }
    
    public TPMSServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TPMSServiceException_Exception(String message, TPMSServiceException tpmsServiceException) {
        super(message);
        this.tpmsServiceException = tpmsServiceException;
    }

    public TPMSServiceException_Exception(String message, TPMSServiceException tpmsServiceException, Throwable cause) {
        super(message, cause);
        this.tpmsServiceException = tpmsServiceException;
    }

    public TPMSServiceException getFaultInfo() {
        return this.tpmsServiceException;
    }
}
