package com.ird.portal.fds.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2021-03-16T17:10:52.636+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "urn:dsat.gov.mo:fds/ws", name = "FDSService")
@XmlSeeAlso({ObjectFactory.class})
public interface FDSService {

    /**
     * reset a transaction fileBatch to null
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/resetFileBatch")
    @RequestWrapper(localName = "resetFileBatch", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "ResetFileBatch")
    @ResponseWrapper(localName = "resetFileBatchResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "ResetFileBatchResponse")
    public void resetFileBatch(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo
    ) throws FDSException;

    /**
     * upload Photo Data
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/uploadPhotoData")
    @RequestWrapper(localName = "uploadPhotoData", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UploadPhotoData")
    @ResponseWrapper(localName = "uploadPhotoDataResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UploadPhotoDataResponse")
    @WebResult(name = "photoResult", targetNamespace = "")
    public PhotoResult uploadPhotoData(
            @WebParam(name = "photo", targetNamespace = "")
                    Photo photo
    ) throws FDSException;

    /**
     * get Operation Docs And Fees Online
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getOperationDocsAndFeesOL")
    @RequestWrapper(localName = "getOperationDocsAndFeesOL", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetOperationDocsAndFeesOL")
    @ResponseWrapper(localName = "getOperationDocsAndFeesOLResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetOperationDocsAndFeesOLResponse")
    @WebResult(name = "operationDocsAndFeesOLRsp", targetNamespace = "")
    public OperationDocsAndFeesOLRsp getOperationDocsAndFeesOL(
            @WebParam(name = "operationDocsAndFeesOLReq", targetNamespace = "")
                    OperationDocsAndFeesOLReq operationDocsAndFeesOLReq
    ) throws FDSException;

    /**
     * free transaction status DayEnd by zoneCode
     * 				and
     * 				paymentDate
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/freeDayEnd")
    @RequestWrapper(localName = "freeDayEnd", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "FreeDayEnd")
    @ResponseWrapper(localName = "freeDayEndResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "FreeDayEndResponse")
    public void freeDayEnd(
            @WebParam(name = "zoneCode", targetNamespace = "")
                    String zoneCode,
            @WebParam(name = "paymentDate", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar paymentDate
    ) throws FDSException;

    /**
     * Get Transactions via a txnNos
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getTransactions")
    @RequestWrapper(localName = "getTransactions", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetTransactions")
    @ResponseWrapper(localName = "getTransactionsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetTransactionsResponse")
    @WebResult(name = "transaction", targetNamespace = "")
    public java.util.List<Transaction> getTransactions(
            @WebParam(name = "txnNos", targetNamespace = "")
                    java.util.List<String> txnNos
    );

    /**
     * update transactinoAction selected selectTime
     * 				selectUid
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/checkUpdateTransactionAction")
    @RequestWrapper(localName = "checkUpdateTransactionAction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CheckUpdateTransactionAction")
    @ResponseWrapper(localName = "checkUpdateTransactionActionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CheckUpdateTransactionActionResponse")
    public void checkUpdateTransactionAction(
            @WebParam(name = "txnNoList", targetNamespace = "")
                    java.util.List<String> txnNoList,
            @WebParam(name = "selectUid", targetNamespace = "")
                    String selectUid
    );

    /**
     * Get related Transactions via a txnNo
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getRelateTransactions")
    @RequestWrapper(localName = "getRelateTransactions", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetRelateTransactions")
    @ResponseWrapper(localName = "getRelateTransactionsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetRelateTransactionsResponse")
    @WebResult(name = "transaction", targetNamespace = "")
    public java.util.List<Transaction> getRelateTransactions(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo
    );

    /**
     * complete a transaction by a given Txn No.
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/completeTransaction")
    @RequestWrapper(localName = "completeTransaction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CompleteTransaction")
    @ResponseWrapper(localName = "completeTransactionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CompleteTransactionResponse")
    public void completeTransaction(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo
    ) throws FDSException;

    /**
     * Get all Issue Organizations from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getIssueOrgs")
    @RequestWrapper(localName = "getIssueOrgs", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetIssueOrgs")
    @ResponseWrapper(localName = "getIssueOrgsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetIssueOrgsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IssueOrg> getIssueOrgs();

    /**
     * Deselect TransactionAction status group from the
     * 				Service Portal Ex
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/deselectTransactionActionGroupEx")
    @RequestWrapper(localName = "deselectTransactionActionGroupEx", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "DeselectTransactionActionGroupEx")
    @ResponseWrapper(localName = "deselectTransactionActionGroupExResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "DeselectTransactionActionGroupExResponse")
    @WebResult(name = "returnObject", targetNamespace = "")
    public ReturnObject deselectTransactionActionGroupEx(
            @WebParam(name = "transActionGroupReq", targetNamespace = "")
                    TransActionGroupReq transActionGroupReq
    );

    /**
     * Get all Streets from the Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getStreets")
    @RequestWrapper(localName = "getStreets", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetStreets")
    @ResponseWrapper(localName = "getStreetsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetStreetsResponse")
    @WebResult(name = "name", targetNamespace = "")
    public java.util.List<Street> getStreets();

    /**
     * Get all Departments from the Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getDepartments")
    @RequestWrapper(localName = "getDepartments", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDepartments")
    @ResponseWrapper(localName = "getDepartmentsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDepartmentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Department> getDepartments();

    /**
     * Get all TransactionForIssues from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getTransactionForIssues")
    @RequestWrapper(localName = "getTransactionForIssues", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetTransactionForIssues")
    @ResponseWrapper(localName = "getTransactionForIssuesResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetTransactionForIssuesResponse")
    @WebResult(name = "transactionForIssue", targetNamespace = "")
    public java.util.List<TransactionForIssue> getTransactionForIssues(
            @WebParam(name = "txnNos", targetNamespace = "")
                    java.util.List<String> txnNos,
            @WebParam(name = "zoneCode", targetNamespace = "")
                    String zoneCode,
            @WebParam(name = "serviceZoneCode", targetNamespace = "")
                    String serviceZoneCode
    );

    /**
     * Get next DateProfile
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getNextDateProfile")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getNextDateProfileResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", partName = "parameters")
    public DateProfile getNextDateProfile(
            @WebParam(partName = "parameters", name = "getNextDateProfileRequest", targetNamespace = "urn:dsat.gov.mo:fds/ws")
                    GetNextDateProfileRequest parameters
    );

    /**
     * submit transactionDetails for epay
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/submitTransactionDetails")
    @RequestWrapper(localName = "submitTransactionDetails", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SubmitTransactionDetails")
    @ResponseWrapper(localName = "submitTransactionDetailsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SubmitTransactionDetailsResponse")
    public void submitTransactionDetails(
            @WebParam(name = "transactionDetails", targetNamespace = "")
                    TransactionDetails transactionDetails
    ) throws FDSException;

    /**
     * get All RequiringDocs Count by docId
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getRequiringDocsCount")
    @RequestWrapper(localName = "getRequiringDocsCount", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetRequiringDocsCount")
    @ResponseWrapper(localName = "getRequiringDocsCountResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetRequiringDocsCountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getRequiringDocsCount(
            @WebParam(name = "docId", targetNamespace = "")
                    long docId
    );

    /**
     * Create a FRESH Transaction in the Service Portal
     * 				with DTO.
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/createTransactionDto")
    @RequestWrapper(localName = "createTransactionDto", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CreateTransactionDto")
    @ResponseWrapper(localName = "createTransactionDtoResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CreateTransactionDtoResponse")
    @WebResult(name = "transaction", targetNamespace = "")
    public Transaction createTransactionDto(
            @WebParam(name = "createTransDto", targetNamespace = "")
                    CreateTransDto createTransDto
    ) throws FDSException;

    /**
     * Generate Case IDs with a given number
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getCaseIDs")
    @RequestWrapper(localName = "getCaseIDs", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetCaseIDs")
    @ResponseWrapper(localName = "getCaseIDsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetCaseIDsResponse")
    @WebResult(name = "name", targetNamespace = "")
    public java.util.List<String> getCaseIDs(
            @WebParam(name = "count", targetNamespace = "")
                    int count
    ) throws FDSException;

    /**
     * Get Transaction Exempt Payment Status for DLM
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getExemptPaymentStatus")
    @RequestWrapper(localName = "getExemptPaymentStatus", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetExemptPaymentStatus")
    @ResponseWrapper(localName = "getExemptPaymentStatusResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetExemptPaymentStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getExemptPaymentStatus(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo
    ) throws FDSException;

    /**
     * allow the client app to submit a Transaction to
     * 				the Service Portal and create payment info.
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/submitPayment")
    @RequestWrapper(localName = "submitPayment", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SubmitPayment")
    @ResponseWrapper(localName = "submitPaymentResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SubmitPaymentResponse")
    public void submitPayment(
            @WebParam(name = "transaction", targetNamespace = "")
                    Transaction transaction,
            @WebParam(name = "callSubmitPaymentAdditional", targetNamespace = "")
                    CallSubmitPaymentAdditional callSubmitPaymentAdditional
    ) throws FDSException;

    /**
     * approve SP Proecss
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/approveSPProecss")
    @RequestWrapper(localName = "approveSPProecss", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "ApproveSPProecss")
    @ResponseWrapper(localName = "approveSPProecssResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "ApproveSPProecssResponse")
    @WebResult(name = "returnObject", targetNamespace = "")
    public ReturnObject approveSPProecss(
            @WebParam(name = "approveReq", targetNamespace = "")
                    ApproveReq approveReq
    ) throws FDSException;

    /**
     * complete transaction status DayEnd by zoneCode
     * 				and paymentDate
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/completeDayEnd")
    @RequestWrapper(localName = "completeDayEnd", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CompleteDayEnd")
    @ResponseWrapper(localName = "completeDayEndResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CompleteDayEndResponse")
    public void completeDayEnd(
            @WebParam(name = "zoneCode", targetNamespace = "")
                    String zoneCode,
            @WebParam(name = "paymentDate", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar paymentDate
    ) throws FDSException;

    /**
     * exec Procedure
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/execProcedure")
    @RequestWrapper(localName = "execProcedure", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "ExecProcedure")
    @ResponseWrapper(localName = "execProcedureResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "ExecProcedureResponse")
    @WebResult(name = "proceOutput", targetNamespace = "")
    public ProceOutput execProcedure(
            @WebParam(name = "proceInput", targetNamespace = "")
                    ProceInput proceInput
    ) throws FDSException;

    /**
     * Get all Rubricas from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getRubricas")
    @RequestWrapper(localName = "getRubricas", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetRubricas")
    @ResponseWrapper(localName = "getRubricasResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetRubricasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Rubrica> getRubricas(
            @WebParam(name = "receiptaCode", targetNamespace = "")
                    String receiptaCode,
            @WebParam(name = "rubricaCode", targetNamespace = "")
                    String rubricaCode
    );

    /**
     * get Issue Zone
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getIssueZone")
    @RequestWrapper(localName = "getIssueZone", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetIssueZone")
    @ResponseWrapper(localName = "getIssueZoneResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetIssueZoneResponse")
    @WebResult(name = "zones", targetNamespace = "")
    public java.util.List<Zone> getIssueZone() throws FDSException;

    /**
     * append Transaction Documents
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/appendTransactionDocs")
    @RequestWrapper(localName = "appendTransactionDocs", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "AppendTransactionDocs")
    @ResponseWrapper(localName = "appendTransactionDocsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "AppendTransactionDocsResponse")
    @WebResult(name = "transDocsRsp", targetNamespace = "")
    public TransDocsRsp appendTransactionDocs(
            @WebParam(name = "transDocsReq", targetNamespace = "")
                    TransDocsReq transDocsReq
    ) throws FDSException;

    /**
     * Get all Zones from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getZones")
    @RequestWrapper(localName = "getZones", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetZones")
    @ResponseWrapper(localName = "getZonesResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetZonesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Zone> getZones();

    /**
     * find ServiceOperations for the FM Receipta to
     * 				view
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/findServiceOperations")
    @RequestWrapper(localName = "findServiceOperations", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "FindServiceOperations")
    @ResponseWrapper(localName = "findServiceOperationsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "FindServiceOperationsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ViewServiceOperation> findServiceOperations(
            @WebParam(name = "receiptaId", targetNamespace = "")
                    long receiptaId
    ) throws FDSException;

    /**
     * Select TransactionActions for the Batch
     * 				Certification DV
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/updateSPStatusForBatch")
    @RequestWrapper(localName = "updateSPStatusForBatch", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UpdateSPStatusForBatch")
    @ResponseWrapper(localName = "updateSPStatusForBatchResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UpdateSPStatusForBatchResponse")
    public void updateSPStatusForBatch(
            @WebParam(name = "txnNos", targetNamespace = "")
                    java.util.List<String> txnNos,
            @WebParam(name = "serviceActionTypes", targetNamespace = "")
                    java.util.List<String> serviceActionTypes,
            @WebParam(name = "uid", targetNamespace = "")
                    String uid
    );

    /**
     * get internetional license
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/loadBusiFileData")
    @RequestWrapper(localName = "loadBusiFileData", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "LoadBusiFileData")
    @ResponseWrapper(localName = "loadBusiFileDataResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "LoadBusiFileDataResponse")
    @WebResult(name = "busiFileDataInfo", targetNamespace = "")
    public BusiFileDataInfo loadBusiFileData(
            @WebParam(name = "busiFileDataParam", targetNamespace = "")
                    BusiFileDataParam busiFileDataParam
    ) throws FDSException;

    /**
     * Get all ID Types from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getIDTypes")
    @RequestWrapper(localName = "getIDTypes", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetIDTypes")
    @ResponseWrapper(localName = "getIDTypesResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetIDTypesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IDType> getIDTypes();

    /**
     * Get all ServiceFees from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getServiceFees")
    @RequestWrapper(localName = "getServiceFees", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetServiceFees")
    @ResponseWrapper(localName = "getServiceFeesResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetServiceFeesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ServiceFee> getServiceFees(
            @WebParam(name = "incomeReceiptaCode", targetNamespace = "")
                    String incomeReceiptaCode,
            @WebParam(name = "incomeRubricaCode", targetNamespace = "")
                    String incomeRubricaCode,
            @WebParam(name = "groupCode", targetNamespace = "")
                    String groupCode,
            @WebParam(name = "code", targetNamespace = "")
                    String code
    );

    /**
     * Search Department from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/searchDepartment")
    @RequestWrapper(localName = "searchDepartment", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SearchDepartment")
    @ResponseWrapper(localName = "searchDepartmentResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SearchDepartmentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Department searchDepartment(
            @WebParam(name = "loginId", targetNamespace = "")
                    String loginId
    );

    /**
     * check DayEnd Precondition by zoneCode
     * 				and
     * 				dayEndDate
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/checkDayEndPrecondition")
    @RequestWrapper(localName = "checkDayEndPrecondition", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CheckDayEndPrecondition")
    @ResponseWrapper(localName = "checkDayEndPreconditionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CheckDayEndPreconditionResponse")
    @WebResult(name = "name", targetNamespace = "")
    public java.util.List<UserProfile> checkDayEndPrecondition(
            @WebParam(name = "dayEndDate", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar dayEndDate,
            @WebParam(name = "zoneCode", targetNamespace = "")
                    String zoneCode
    ) throws FDSException;

    /**
     * Get transaction DayEnd Or Balance Count
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getDayEndOrBalanceCount")
    @RequestWrapper(localName = "getDayEndOrBalanceCount", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDayEndOrBalanceCount")
    @ResponseWrapper(localName = "getDayEndOrBalanceCountResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDayEndOrBalanceCountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getDayEndOrBalanceCount(
            @WebParam(name = "loginId", targetNamespace = "")
                    String loginId,
            @WebParam(name = "zoneCode", targetNamespace = "")
                    String zoneCode
    );

    /**
     * send SMS or not
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/isNeedToSendSMS")
    @RequestWrapper(localName = "isNeedToSendSMS", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "IsNeedToSendSMS")
    @ResponseWrapper(localName = "isNeedToSendSMSResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "IsNeedToSendSMSResponse")
    @WebResult(name = "isNeedToSendSMS", targetNamespace = "")
    public boolean isNeedToSendSMS(
            @WebParam(name = "idTypeCode", targetNamespace = "")
                    String idTypeCode,
            @WebParam(name = "idNo", targetNamespace = "")
                    String idNo,
            @WebParam(name = "docId", targetNamespace = "")
                    long docId,
            @WebParam(name = "vId", targetNamespace = "")
                    long vId,
            @WebParam(name = "driverLicType", targetNamespace = "")
                    String driverLicType,
            @WebParam(name = "driverLicNo", targetNamespace = "")
                    String driverLicNo,
            @WebParam(name = "categoryTypeCode", targetNamespace = "")
                    String categoryTypeCode,
            @WebParam(name = "categoryNo", targetNamespace = "")
                    String categoryNo,
            @WebParam(name = "uid", targetNamespace = "")
                    String uid
    ) throws FDSException;

    /**
     * Update Transaction Doc/Fee Remark、Url、SkipFlag
     * 				and License Issue Zone
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/updateTransaction")
    @RequestWrapper(localName = "updateTransaction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UpdateTransaction")
    @ResponseWrapper(localName = "updateTransactionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UpdateTransactionResponse")
    public void updateTransaction(
            @WebParam(name = "transaction", targetNamespace = "")
                    Transaction transaction
    );

    /**
     * Create a FRESH Slave Transaction in the Service
     * 				Portal.
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/createSlaveTransaction")
    @RequestWrapper(localName = "createSlaveTransaction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CreateSlaveTransaction")
    @ResponseWrapper(localName = "createSlaveTransactionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CreateSlaveTransactionResponse")
    @WebResult(name = "transaction", targetNamespace = "")
    public Transaction createSlaveTransaction(
            @WebParam(name = "serviceOperationCode", targetNamespace = "")
                    String serviceOperationCode,
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo,
            @WebParam(name = "loginId", targetNamespace = "")
                    String loginId,
            @WebParam(name = "incomeIP", targetNamespace = "")
                    String incomeIP,
            @WebParam(name = "completeOnCreation", targetNamespace = "")
                    boolean completeOnCreation
    ) throws FDSException;

    /**
     * Get Transactions is Already Issue License
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getIssueLicenseTxnnos")
    @RequestWrapper(localName = "getIssueLicenseTxnnos", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetIssueLicenseTxnnos")
    @ResponseWrapper(localName = "getIssueLicenseTxnnosResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetIssueLicenseTxnnosResponse")
    @WebResult(name = "issueTxnNo", targetNamespace = "")
    public java.util.List<String> getIssueLicenseTxnnos(
            @WebParam(name = "txnNos", targetNamespace = "")
                    java.util.List<String> txnNos,
            @WebParam(name = "zoneCode", targetNamespace = "")
                    String zoneCode
    );

    /**
     * get no dayend zone count
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getDayEndControlView")
    @RequestWrapper(localName = "getDayEndControlView", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDayEndControlView")
    @ResponseWrapper(localName = "getDayEndControlViewResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDayEndControlViewResponse")
    @WebResult(name = "name", targetNamespace = "")
    public java.util.List<DayEndControlView> getDayEndControlView() throws FDSException;

    /**
     * Create a FRESH Transaction in the Service Portal.
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/createTransaction")
    @RequestWrapper(localName = "createTransaction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CreateTransaction")
    @ResponseWrapper(localName = "createTransactionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CreateTransactionResponse")
    @WebResult(name = "transaction", targetNamespace = "")
    public Transaction createTransaction(
            @WebParam(name = "serviceOperationCode", targetNamespace = "")
                    String serviceOperationCode,
            @WebParam(name = "loginId", targetNamespace = "")
                    String loginId,
            @WebParam(name = "incomeIP", targetNamespace = "")
                    String incomeIP,
            @WebParam(name = "completeOnCreation", targetNamespace = "")
                    boolean completeOnCreation
    ) throws FDSException;

    /**
     * Get all VehicleTypes from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getVehicleTypes")
    @RequestWrapper(localName = "getVehicleTypes", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetVehicleTypes")
    @ResponseWrapper(localName = "getVehicleTypesResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetVehicleTypesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<VehicleType> getVehicleTypes();

    /**
     * Get next Working Day
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getNextWorkingDay")
    @RequestWrapper(localName = "getNextWorkingDay", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetNextWorkingDay")
    @ResponseWrapper(localName = "getNextWorkingDayResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetNextWorkingDayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public javax.xml.datatype.XMLGregorianCalendar getNextWorkingDay(
            @WebParam(name = "date", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar date
    );

    /**
     * Get all getServiceOperations from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getServiceOperations")
    @RequestWrapper(localName = "getServiceOperations", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetServiceOperations")
    @ResponseWrapper(localName = "getServiceOperationsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetServiceOperationsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ServiceOperation> getServiceOperations();

    /**
     * get RequiringDocs Count by txnNo
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getRequiringDocsCountByTxnNo")
    @RequestWrapper(localName = "getRequiringDocsCountByTxnNo", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetRequiringDocsCountByTxnNo")
    @ResponseWrapper(localName = "getRequiringDocsCountByTxnNoResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetRequiringDocsCountByTxnNoResponse")
    @WebResult(name = "RequiringDocsInfos", targetNamespace = "")
    public java.util.List<RequiringDocsInfo> getRequiringDocsCountByTxnNo(
            @WebParam(name = "txnNos", targetNamespace = "")
                    java.util.List<String> txnNos
    );

    /**
     * auto Create And Complete OL Transaction
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/autoCreateAndCompleteOLTransaction")
    @RequestWrapper(localName = "autoCreateAndCompleteOLTransaction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "AutoCreateAndCompleteOLTransaction")
    @ResponseWrapper(localName = "autoCreateAndCompleteOLTransactionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "AutoCreateAndCompleteOLTransactionResponse")
    @WebResult(name = "createOnlineTransRtn", targetNamespace = "")
    public CreateOnlineTransRtn autoCreateAndCompleteOLTransaction(
            @WebParam(name = "createOnlineTransDto", targetNamespace = "")
                    CreateOnlineTransDto createOnlineTransDto
    ) throws FDSException;

    /**
     * Create a FRESH Transaction in the Service Portal
     * 				by increasing the Document Sequence of the most updated Transaction
     * 				with the given caseId.
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/increaseTransaction")
    @RequestWrapper(localName = "increaseTransaction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "IncreaseTransaction")
    @ResponseWrapper(localName = "increaseTransactionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "IncreaseTransactionResponse")
    @WebResult(name = "transaction", targetNamespace = "")
    public Transaction increaseTransaction(
            @WebParam(name = "caseId", targetNamespace = "")
                    String caseId
    ) throws FDSException;

    /**
     * Get Transaction Payment Amount for DLM
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getTransactionPaymentAmount")
    @RequestWrapper(localName = "getTransactionPaymentAmount", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetTransactionPaymentAmount")
    @ResponseWrapper(localName = "getTransactionPaymentAmountResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetTransactionPaymentAmountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double getTransactionPaymentAmount(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo
    ) throws FDSException;

    /**
     * Get DateProfiles within a range
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getDateProfiles")
    @RequestWrapper(localName = "getDateProfiles", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDateProfiles")
    @ResponseWrapper(localName = "getDateProfilesResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDateProfilesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<DateProfile> getDateProfiles(
            @WebParam(name = "startDate", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar endDate
    );

    /**
     * Deselect TransactionAction status group from the
     * 				Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/deselectTransactionActionGroup")
    @RequestWrapper(localName = "deselectTransactionActionGroup", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "DeselectTransactionActionGroup")
    @ResponseWrapper(localName = "deselectTransactionActionGroupResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "DeselectTransactionActionGroupResponse")
    public void deselectTransactionActionGroup(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo,
            @WebParam(name = "serviceActionType", targetNamespace = "")
                    String serviceActionType
    );

    /**
     * Get Transaction Payment Information for VSS
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getPaymentInformation")
    @RequestWrapper(localName = "getPaymentInformation", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetPaymentInformation")
    @ResponseWrapper(localName = "getPaymentInformationResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetPaymentInformationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PaymentInfo getPaymentInformation(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo
    ) throws FDSException;

    /**
     * allow the client app to submit a Transaction to
     * 				the Service Portal. Such a Transaction should be created by the
     * 				Service Portal at first.
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/submit")
    @RequestWrapper(localName = "submit", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "Submit")
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SubmitResponse")
    public void submit(
            @WebParam(name = "transaction", targetNamespace = "")
                    Transaction transaction
    ) throws FDSException;

    /**
     * Get DateProfile of a date
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getDateProfile")
    @RequestWrapper(localName = "getDateProfile", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDateProfile")
    @ResponseWrapper(localName = "getDateProfileResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDateProfileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DateProfile getDateProfile(
            @WebParam(name = "date", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar date
    );

    /**
     * Batch Deselect Independent TransactionAction
     * 				status
     * 				from the Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/batchDeselectIndependentTransactionAction")
    @RequestWrapper(localName = "batchDeselectIndependentTransactionAction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "BatchDeselectIndependentTransactionAction")
    @ResponseWrapper(localName = "batchDeselectIndependentTransactionActionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "BatchDeselectIndependentTransactionActionResponse")
    public void batchDeselectIndependentTransactionAction(
            @WebParam(name = "txnNos", targetNamespace = "")
                    java.util.List<String> txnNos,
            @WebParam(name = "serviceActionTypes", targetNamespace = "")
                    java.util.List<String> serviceActionTypes
    );

    /**
     * submit transactionDetails for epay
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getMasterTxnNos")
    @RequestWrapper(localName = "getMasterTxnNos", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetMasterTxnNos")
    @ResponseWrapper(localName = "getMasterTxnNosResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetMasterTxnNosResponse")
    @WebResult(name = "txnNos", targetNamespace = "")
    public java.util.List<String> getMasterTxnNos(
            @WebParam(name = "count", targetNamespace = "")
                    int count
    ) throws FDSException;

    /**
     * batch Update DTS Description for SPIN
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/batchUpdateDTSDesc")
    @RequestWrapper(localName = "batchUpdateDTSDesc", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "BatchUpdateDTSDesc")
    @ResponseWrapper(localName = "batchUpdateDTSDescResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "BatchUpdateDTSDescResponse")
    public void batchUpdateDTSDesc(
            @WebParam(name = "dtsParams", targetNamespace = "")
                    java.util.List<DTSParam> dtsParams,
            @WebParam(name = "loginId", targetNamespace = "")
                    String loginId
    );

    /**
     * Search Zone from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/searchZone")
    @RequestWrapper(localName = "searchZone", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SearchZone")
    @ResponseWrapper(localName = "searchZoneResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SearchZoneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Zone searchZone(
            @WebParam(name = "incomeIP", targetNamespace = "")
                    String incomeIP
    );

    /**
     * Get DayEndDetails from Service Portal by zoneCode
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getDayEndDetails")
    @RequestWrapper(localName = "getDayEndDetails", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDayEndDetails")
    @ResponseWrapper(localName = "getDayEndDetailsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetDayEndDetailsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<DayEndDetails> getDayEndDetails(
            @WebParam(name = "zoneCode", targetNamespace = "")
                    String zoneCode,
            @WebParam(name = "first", targetNamespace = "")
                    long first,
            @WebParam(name = "count", targetNamespace = "")
                    long count
    );

    /**
     * Get all Services from Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getServices")
    @RequestWrapper(localName = "getServices", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetServices")
    @ResponseWrapper(localName = "getServicesResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetServicesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Service> getServices();

    /**
     * As the users need to know the Workflow Status of
     * 				a Transaction in an individual Client App. This method is used to
     * 				update these Workflow Statuses. However, the Workflow Status of a
     * 				Transaction defined in the Service Portal is independennt from
     * 				thoses submitted from the Client Apps.a
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/updateWorkflowStatus")
    @RequestWrapper(localName = "updateWorkflowStatus", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UpdateWorkflowStatus")
    @ResponseWrapper(localName = "updateWorkflowStatusResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UpdateWorkflowStatusResponse")
    public void updateWorkflowStatus(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo,
            @WebParam(name = "statusKey", targetNamespace = "")
                    String statusKey,
            @WebParam(name = "statusDisplayZh", targetNamespace = "")
                    String statusDisplayZh,
            @WebParam(name = "statusDisplayPt", targetNamespace = "")
                    String statusDisplayPt
    ) throws FDSException;

    /**
     * Create a FRESH Transaction in the Service
     * 				Portal.Then get the complete URL.
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/autoCreateAndCompleteTransaction")
    @RequestWrapper(localName = "autoCreateAndCompleteTransaction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "AutoCreateAndCompleteTransaction")
    @ResponseWrapper(localName = "autoCreateAndCompleteTransactionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "AutoCreateAndCompleteTransactionResponse")
    @WebResult(name = "transaction", targetNamespace = "")
    public Transaction autoCreateAndCompleteTransaction(
            @WebParam(name = "serviceFeeRequests", targetNamespace = "")
                    java.util.List<ServiceFeeRequestVSS> serviceFeeRequests,
            @WebParam(name = "payment", targetNamespace = "")
                    Payment payment,
            @WebParam(name = "createTransInfo", targetNamespace = "")
                    CreateTransInfo createTransInfo
    ) throws FDSException;

    /**
     * Count DayEndDates from Service Portal by zoneCode
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/countDayEndDates")
    @RequestWrapper(localName = "countDayEndDates", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CountDayEndDates")
    @ResponseWrapper(localName = "countDayEndDatesResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "CountDayEndDatesResponse")
    @WebResult(name = "counts", targetNamespace = "")
    public long countDayEndDates(
            @WebParam(name = "zoneCode", targetNamespace = "")
                    String zoneCode
    );

    /**
     * Select TransactionActions from the Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/selectTransactionActions")
    @RequestWrapper(localName = "selectTransactionActions", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SelectTransactionActions")
    @ResponseWrapper(localName = "selectTransactionActionsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "SelectTransactionActionsResponse")
    public void selectTransactionActions(
            @WebParam(name = "keys", targetNamespace = "")
                    java.util.List<TransactionActionKey> keys,
            @WebParam(name = "uid", targetNamespace = "")
                    String uid
    );

    /**
     * Deselect TransactionAction status from the
     * 				Service Portal
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/deselectTransactionAction")
    @RequestWrapper(localName = "deselectTransactionAction", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "DeselectTransactionAction")
    @ResponseWrapper(localName = "deselectTransactionActionResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "DeselectTransactionActionResponse")
    public void deselectTransactionAction(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo
    );

    /**
     * get Operation Codes From ServicePrivilege By
     * 				LoginId
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getOperationCodes")
    @RequestWrapper(localName = "getOperationCodes", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetOperationCodes")
    @ResponseWrapper(localName = "getOperationCodesResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetOperationCodesResponse")
    @WebResult(name = "operationCodes", targetNamespace = "")
    public java.util.List<String> getOperationCodes(
            @WebParam(name = "loginId", targetNamespace = "")
                    String loginId
    );

    /**
     * Get Transaction Information for SPIN
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getTransactionInfo")
    @RequestWrapper(localName = "getTransactionInfo", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetTransactionInfo")
    @ResponseWrapper(localName = "getTransactionInfoResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetTransactionInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public TransactionInfo getTransactionInfo(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo
    ) throws FDSException;

    /**
     * update Transaction Documents
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/updateTransactionDocs")
    @RequestWrapper(localName = "updateTransactionDocs", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UpdateTransactionDocs")
    @ResponseWrapper(localName = "updateTransactionDocsResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "UpdateTransactionDocsResponse")
    @WebResult(name = "transDocsRsp", targetNamespace = "")
    public TransDocsRsp updateTransactionDocs(
            @WebParam(name = "transDocsReq", targetNamespace = "")
                    TransDocsReq transDocsReq
    ) throws FDSException;

    /**
     * Get FeeEntry Amount for DLM
     * 			
     */
    @WebMethod(action = "urn:dsat.gov.mo:fds/ws/getFeeEntryAmount")
    @RequestWrapper(localName = "getFeeEntryAmount", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetFeeEntryAmount")
    @ResponseWrapper(localName = "getFeeEntryAmountResponse", targetNamespace = "urn:dsat.gov.mo:fds/ws", className = "GetFeeEntryAmountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double getFeeEntryAmount(
            @WebParam(name = "txnNo", targetNamespace = "")
                    String txnNo,
            @WebParam(name = "serviceFeeCode", targetNamespace = "")
                    String serviceFeeCode
    ) throws FDSException;
}
