
package com.ird.portal.mega.tpms.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2021-02-25T09:49:25.605+08:00
 * Generated source version: 3.0.16
 * 
 */
public final class TPMSService_TPMSServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.tpms.dsat.mega.com/", "TPMSServiceService");

    private static final Logger logger = LoggerFactory.getLogger(TPMSService_TPMSServicePort_Client.class);

    private TPMSService_TPMSServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = TPMSServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                logger.error("wsdlFile >>>>>>>>>",e);
            }
        }
      
        TPMSServiceService ss = new TPMSServiceService(wsdlURL, SERVICE_NAME);
        TPMSService port = ss.getTPMSServicePort();  
        
        {
        System.out.println("Invoking queryDocId...");
        Long _queryDocId_taxiCertNo = null;
        ActionParam _queryDocId_actionParam = null;
        Long _queryDocId__return = port.queryDocId(_queryDocId_taxiCertNo, _queryDocId_actionParam);
        System.out.println("queryDocId.result=" + _queryDocId__return);


        }
        {
        System.out.println("Invoking getTPMSSendDate...");
        Long _getTPMSSendDate_taxiProCertNo = null;
        Long _getTPMSSendDate_docId = null;
        TPMSSendDate _getTPMSSendDate__return = port.getTPMSSendDate(_getTPMSSendDate_taxiProCertNo, _getTPMSSendDate_docId);
        System.out.println("getTPMSSendDate.result=" + _getTPMSSendDate__return);


        }
        {
        System.out.println("Invoking reprintTaxiProCert...");
        ReprintTaxiProCertDto _reprintTaxiProCert_reprintTaxiProCertDto = null;
        ActionParam _reprintTaxiProCert_actionParam = null;
        port.reprintTaxiProCert(_reprintTaxiProCert_reprintTaxiProCertDto, _reprintTaxiProCert_actionParam);


        }
        {
        System.out.println("Invoking checkProofInfo...");
        TPMSProofFile _checkProofInfo_tpmsProofFile = null;
        TPMSProofFileData _checkProofInfo__return = port.checkProofInfo(_checkProofInfo_tpmsProofFile);
        System.out.println("checkProofInfo.result=" + _checkProofInfo__return);


        }
        {
        System.out.println("Invoking updateTPMSCustomer...");
        TPMSCustomer _updateTPMSCustomer_customer = null;
        ActionParam _updateTPMSCustomer_actionParam = null;
        port.updateTPMSCustomer(_updateTPMSCustomer_customer, _updateTPMSCustomer_actionParam);


        }
        {
        System.out.println("Invoking renewTaxiProCert...");
        TPMSProCertReq _renewTaxiProCert_tpmsProCertReq = null;
        java.util.List<String> _renewTaxiProCert_modifiedCodes = null;
        ActionParam _renewTaxiProCert_actionParam = null;
        port.renewTaxiProCert(_renewTaxiProCert_tpmsProCertReq, _renewTaxiProCert_modifiedCodes, _renewTaxiProCert_actionParam);


        }
        {
        System.out.println("Invoking getTPMSDataFine...");
        Long _getTPMSDataFine_docId = null;
        ActionParam _getTPMSDataFine_actionParam = null;
        String _getTPMSDataFine_taxiCertNo = "";
        TPMSData _getTPMSDataFine__return = port.getTPMSDataFine(_getTPMSDataFine_docId, _getTPMSDataFine_actionParam, _getTPMSDataFine_taxiCertNo);
        System.out.println("getTPMSDataFine.result=" + _getTPMSDataFine__return);


        }
        {
        System.out.println("Invoking issueTPMSProCert...");
        TPMSCustomer _issueTPMSProCert_customer = null;
        ActionParam _issueTPMSProCert_actionParam = null;
        TPMSProCert _issueTPMSProCert__return = port.issueTPMSProCert(_issueTPMSProCert_customer, _issueTPMSProCert_actionParam);
        System.out.println("issueTPMSProCert.result=" + _issueTPMSProCert__return);


        }
        {
        System.out.println("Invoking getTaxiProCertPrintNo...");
        Long _getTaxiProCertPrintNo_taxiProCertNo = null;
        java.util.List<String> _getTaxiProCertPrintNo_modifiedCodes = null;
        ActionParam _getTaxiProCertPrintNo_actionParam = null;
        String _getTaxiProCertPrintNo_spTxnno = "";
        String _getTaxiProCertPrintNo__return = port.getTaxiProCertPrintNo(_getTaxiProCertPrintNo_taxiProCertNo, _getTaxiProCertPrintNo_modifiedCodes, _getTaxiProCertPrintNo_actionParam, _getTaxiProCertPrintNo_spTxnno);
        System.out.println("getTaxiProCertPrintNo.result=" + _getTaxiProCertPrintNo__return);


        }
        {
        System.out.println("Invoking backendCompleteIssue...");
        TPMSProCertReq _backendCompleteIssue_tpmsProCertReq = null;
        ActionParam _backendCompleteIssue_actionParam = null;
        String _backendCompleteIssue__return = port.backendCompleteIssue(_backendCompleteIssue_tpmsProCertReq, _backendCompleteIssue_actionParam);
        System.out.println("backendCompleteIssue.result=" + _backendCompleteIssue__return);


        }
        {
        System.out.println("Invoking isExistTaxiCert...");
        Long _isExistTaxiCert_docId = null;
        TPMSCertExistsResult _isExistTaxiCert__return = port.isExistTaxiCert(_isExistTaxiCert_docId);
        System.out.println("isExistTaxiCert.result=" + _isExistTaxiCert__return);


        }
        {
        System.out.println("Invoking tpmsAction...");
        String _tpmsAction_action = "";
        String _tpmsAction_param = "";
        String _tpmsAction__return = port.tpmsAction(_tpmsAction_action, _tpmsAction_param);
        System.out.println("tpmsAction.result=" + _tpmsAction__return);


        }
        {
        System.out.println("Invoking queryProofFiles...");
        TPMSProofFile _queryProofFiles_tpmsProofFile = null;
        java.util.List<TPMSProofFile> _queryProofFiles__return = port.queryProofFiles(_queryProofFiles_tpmsProofFile);
        System.out.println("queryProofFiles.result=" + _queryProofFiles__return);


        }
        {
        System.out.println("Invoking getTPMSData...");
        Long _getTPMSData_docId = null;
        ActionParam _getTPMSData_actionParam = null;
        TPMSData _getTPMSData__return = port.getTPMSData(_getTPMSData_docId, _getTPMSData_actionParam);
        System.out.println("getTPMSData.result=" + _getTPMSData__return);


        }
        {
        System.out.println("Invoking rollbackPayFine...");
        ActionParam _rollbackPayFine_actionParam = null;
        java.util.List<TPMSProCertFine> _rollbackPayFine_tpmsProCertFines = null;
        port.rollbackPayFine(_rollbackPayFine_actionParam, _rollbackPayFine_tpmsProCertFines);


        }
        {
        System.out.println("Invoking deleteCandidateInfo...");
        TPMSDeleteParam _deleteCandidateInfo_tpmsDeleteParam = null;
        ActionParam _deleteCandidateInfo_actionParam = null;
        port.deleteCandidateInfo(_deleteCandidateInfo_tpmsDeleteParam, _deleteCandidateInfo_actionParam);


        }
        {
        System.out.println("Invoking validateCertLabelNo...");
        Long _validateCertLabelNo_certLabelNo = null;
        String _validateCertLabelNo_spTxnno = "";
        boolean _validateCertLabelNo_isReprint = false;
        try {
            port.validateCertLabelNo(_validateCertLabelNo_certLabelNo, _validateCertLabelNo_spTxnno, _validateCertLabelNo_isReprint);

        } catch (TPMSServiceException_Exception e) { 
            System.out.println("Expected exception: TPMSServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateDocID...");
        Long _updateDocID_oldDocId = null;
        Long _updateDocID_newDocId = null;
        ActionParam _updateDocID_actionParam = null;
        port.updateDocID(_updateDocID_oldDocId, _updateDocID_newDocId, _updateDocID_actionParam);


        }
        {
        System.out.println("Invoking getTPMSCertInfoList...");
        java.util.List<Long> _getTPMSCertInfoList_arg0 = null;
        String _getTPMSCertInfoList_arg1 = "";
        java.util.List<TaxiDrivingLicense> _getTPMSCertInfoList__return = port.getTPMSCertInfoList(_getTPMSCertInfoList_arg0, _getTPMSCertInfoList_arg1);
        System.out.println("getTPMSCertInfoList.result=" + _getTPMSCertInfoList__return);


        }
        {
        System.out.println("Invoking cancelTPMSProCert...");
        String _cancelTPMSProCert_txnNo = "";
        Long _cancelTPMSProCert_docId = null;
        Long _cancelTPMSProCert_taxiProCertNo = null;
        int _cancelTPMSProCert_applicationType = 0;
        ActionParam _cancelTPMSProCert_actionParam = null;
        port.cancelTPMSProCert(_cancelTPMSProCert_txnNo, _cancelTPMSProCert_docId, _cancelTPMSProCert_taxiProCertNo, _cancelTPMSProCert_applicationType, _cancelTPMSProCert_actionParam);


        }
        {
        System.out.println("Invoking getExamTime...");
        TPMSTransaction _getExamTime_txn = null;
        ActionParam _getExamTime_actionParam = null;
        try {
            TPMSExamTime _getExamTime__return = port.getExamTime(_getExamTime_txn, _getExamTime_actionParam);
            System.out.println("getExamTime.result=" + _getExamTime__return);

        } catch (TPMSServiceException_Exception e) { 
            System.out.println("Expected exception: TPMSServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTPMSCertInfo...");
        Long _getTPMSCertInfo_docId = null;
        String _getTPMSCertInfo_status = "";
        java.util.List<TaxiDrivingLicense> _getTPMSCertInfo__return = port.getTPMSCertInfo(_getTPMSCertInfo_docId, _getTPMSCertInfo_status);
        System.out.println("getTPMSCertInfo.result=" + _getTPMSCertInfo__return);


        }
        {
        System.out.println("Invoking payFine...");
        String _payFine_txnNo = "";
        java.util.List<TPMSProCertFine> _payFine_tpmsProCertFines = null;
        ActionParam _payFine_actionParam = null;
        Integer _payFine__return = port.payFine(_payFine_txnNo, _payFine_tpmsProCertFines, _payFine_actionParam);
        System.out.println("payFine.result=" + _payFine__return);


        }
        {
        System.out.println("Invoking rollbackRenewalAndExpiryDate...");
        String _rollbackRenewalAndExpiryDate_txnno = "";
        Long _rollbackRenewalAndExpiryDate_taxiCertNo = null;
        port.rollbackRenewalAndExpiryDate(_rollbackRenewalAndExpiryDate_txnno, _rollbackRenewalAndExpiryDate_taxiCertNo);


        }
        {
        System.out.println("Invoking getTPMSUntreatedFineCount...");
        Long _getTPMSUntreatedFineCount_certNo = null;
        Integer _getTPMSUntreatedFineCount__return = port.getTPMSUntreatedFineCount(_getTPMSUntreatedFineCount_certNo);
        System.out.println("getTPMSUntreatedFineCount.result=" + _getTPMSUntreatedFineCount__return);


        }
        {
        System.out.println("Invoking getExamArrangements...");
        java.util.List<ExamSchedules> _getExamArrangements__return = port.getExamArrangements();
        System.out.println("getExamArrangements.result=" + _getExamArrangements__return);


        }
        {
        System.out.println("Invoking getTPMSCertDocIdAndDocSeq...");
        Long _getTPMSCertDocIdAndDocSeq_certNo = null;
        TPMSCustomer _getTPMSCertDocIdAndDocSeq__return = port.getTPMSCertDocIdAndDocSeq(_getTPMSCertDocIdAndDocSeq_certNo);
        System.out.println("getTPMSCertDocIdAndDocSeq.result=" + _getTPMSCertDocIdAndDocSeq__return);


        }
        {
        System.out.println("Invoking getTPMSSysParam...");
        TPMSSysParam _getTPMSSysParam__return = port.getTPMSSysParam();
        System.out.println("getTPMSSysParam.result=" + _getTPMSSysParam__return);


        }

        System.exit(0);
    }

}
