package com.ird.portal.mega.tpms.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2021-02-25T09:49:25.772+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebServiceClient(name = "TPMSServiceService", 
                  wsdlLocation = "file:/C:/software/ws/TPMSService.wsdl",
                  targetNamespace = "http://service.tpms.dsat.mega.com/") 
public class TPMSServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.tpms.dsat.mega.com/", "TPMSServiceService");
    public final static QName TPMSServicePort = new QName("http://service.tpms.dsat.mega.com/", "TPMSServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/software/ws/TPMSService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TPMSServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/software/ws/TPMSService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TPMSServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TPMSServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TPMSServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TPMSServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TPMSServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TPMSServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns TPMSService
     */
    @WebEndpoint(name = "TPMSServicePort")
    public TPMSService getTPMSServicePort() {
        return super.getPort(TPMSServicePort, TPMSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TPMSService
     */
    @WebEndpoint(name = "TPMSServicePort")
    public TPMSService getTPMSServicePort(WebServiceFeature... features) {
        return super.getPort(TPMSServicePort, TPMSService.class, features);
    }

}
